//! One handler per file, each mapping a single `RpcClient` method to its
//! HTTP route. Reads borrow only the store; the two mutating handlers
//! (start_run, decide) build an engine with the live goose transport.

mod add_group_member;
mod create_group;
mod create_integration;
mod create_reminder;
mod create_space;
mod create_task;
mod create_workflow;
mod decide;
mod dismiss_reminder;
mod fire_workflow;
mod goose_settings;
mod grant_membership;
mod health;
mod ingress;
mod list_calendar;
mod list_decisions;
mod list_integrations;
mod list_members;
mod list_pending;
mod list_reminders;
mod list_runs;
mod list_spaces;
mod list_tasks;
mod list_workflows;
mod record_decision;
mod set_feed_visibility;
mod set_workflow_status;
mod start_run;
mod subscribe;
mod timeline;
mod upsert_calendar;

pub use add_group_member::add_group_member;
pub use create_group::create_group;
pub use create_integration::create_integration;
pub use create_reminder::create_reminder;
pub use create_space::create_space;
pub use create_task::create_task;
pub use create_workflow::create_workflow;
pub use decide::decide;
pub use dismiss_reminder::dismiss_reminder;
pub use fire_workflow::fire_workflow;
pub use goose_settings::{get_goose_config, list_goose_providers, set_goose_config};
pub use grant_membership::grant_membership;
pub use health::health;
pub use ingress::ingress;
pub use list_calendar::list_calendar;
pub use list_decisions::list_decisions;
pub use list_integrations::list_integrations;
pub use list_members::list_members;
pub use list_pending::list_pending;
pub use list_reminders::list_reminders;
pub use list_runs::list_runs;
pub use list_spaces::list_spaces;
pub use list_tasks::list_tasks;
pub use list_workflows::list_workflows;
pub use record_decision::record_decision;
pub use set_feed_visibility::set_feed_visibility;
pub use set_workflow_status::{disable_workflow, enable_workflow};
pub use start_run::start_run;
pub use subscribe::subscribe;
pub use timeline::timeline;
pub use upsert_calendar::upsert_calendar;
